### ISSUE TITLE
Latest registered version of ACE.jl not pushed to ACEsuit/ACE.jl repository

### ISSUE THREAD

**Issue by MatthiasSachs** [ACEsuit/ACEregistry#8]
@cortner: I just noticed that the new version (0.12.46) of ACE.jl has been registered here:

["0.12.46"]
git-tree-sha1 = "f509917bb160462da82b97fa9210170a06d2a533"

However, the relevant commit has, as far as I can see, not been pushed to ACEsuit/ACE.jl.

**Comment by cortner** [comment]
fixing it now. Thank you for tracking this down and sorry for the delay.

**Comment by cortner** [comment]
should now be fixed. Please check?
